//ASYNC ACTIONS
//fetch
export const FETCH_DATA_BEGIN = "FETCH_DATA_BEGIN";
export const FETCH_APPROVED_QUESTIONS_FAILURE =
  "FETCH_APPROVED_QUESTIONS_FAILURE";
export const FETCH_APPROVED_QUESTIONS_SUCCEEDED =
  "FETCH_APPROVED_QUESTIONS_SUCCEEDED";
export const FETCH_PENDING_QUESTIONS_SUCCEEDED =
  "FETCH_PENDING_QUESTIONS_SUCCEEDED";
export const FETCH_PENDING_QUESTIONS_FAILURE =
  "FETCH_PENDING_QUESTIONS_FAILURE";
//post
export const POST_DATA_BEGIN = "POST_DATA_BEGIN";
export const POST_USER_QUESTION_FAILURE = "POST_USER_QUESTION_FAILURE";
export const POST_USER_QUESTION_SUCCEEDED = "POST_USER_QUESTION_SUCCEEDED";
export const POST_RATE_QUESTION_SUCCEEDED =
  "POST_GIVE_LIKE_TO_QUESTION_SUCCEEDED";
export const POST_RATE_QUESTION_FAILURE = "POST_GIVE_LIKE_TO_QUESTION_FAILURE";
// SYNC ACTIONS

export const ANSWER_HANDLER = "ANSWER_HANDLER";
export const NAVIGATION_HANDLER = "NAVIGATION_HANDLER";
export const FILTER_PENDING_QUESTIONS = "FILTER_PENDING_QUESTIONS";
export const GIVE_CHOSEN_APPROVED_QUESTIONS = "GIVE_CHOSEN_APPROVED_QUESTIONS";
export const CHANGE_CHOSEN_TECHNOLOGY = "CHANGE_CHOSEN_TECHNOLOGY";
